version: "3"
services:
  chromeless:
    build: ..
  pytest:
    image: chromeless-pytest
    volumes:
      - ../chromeless:/local/chromeless
    working_dir: /local
    environment:
      - CHROMELESS_SERVER_FUNCTION_NAME=local
    depends_on:
      - "chromeless"
